# Generated by Django 5.1.4 on 2025-01-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=255)),
                ('timestamp', models.BigIntegerField()),
                ('path', models.CharField(max_length=255)),
                ('response_code', models.IntegerField()),
                ('processing_time', models.IntegerField()),
                ('method', models.CharField(max_length=10)),
            ],
        ),
    ]
